name: eduportal-u

# Configuración de la región
region: nyc

# ============================================
# SERVICIO BACKEND (API)
# ============================================
services:
  - name: backend
    github:
      repo: estebanIoI/EduportalU
      branch: main
      deploy_on_push: true
    # Usar el Dockerfile existente
    dockerfile_path: Dockerfile
    source_dir: /backend
    
    # Configuración HTTP
    http_port: 5000
    
    # Rutas de la API
    routes:
      - path: /api
    
    # Plan de instancia (basic-xxs es el más económico)
    instance_size_slug: basic-xxs
    instance_count: 1
    
    # Variables de entorno del backend
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      # Configurar estas variables en el panel de DigitalOcean
      - key: DB_HOST
        type: SECRET
      - key: DB_USER
        type: SECRET
      - key: DB_PASSWORD
        type: SECRET
      - key: DB_NAME
        type: SECRET
      - key: DB_PORT
        value: "3306"
      - key: JWT_SECRET
        type: SECRET
    
    # Health check
    health_check:
      http_path: /api/v1/health
      initial_delay_seconds: 10
      period_seconds: 30

# ============================================
# SITIO ESTÁTICO / FRONTEND (Next.js)
# ============================================
  - name: frontend
    github:
      repo: estebanIoI/EduportalU
      branch: main
      deploy_on_push: true
    # Usar el Dockerfile existente
    dockerfile_path: Dockerfile
    source_dir: /frontend
    
    # Configuración HTTP
    http_port: 3000
    
    # Rutas del frontend (raíz)
    routes:
      - path: /
    
    # Plan de instancia
    instance_size_slug: basic-xxs
    instance_count: 1
    
    # Variables de entorno del frontend
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      # La URL de la API se configurará dinámicamente
      - key: NEXT_PUBLIC_API_URL
        value: ${backend.PUBLIC_URL}/api/v1
      - key: NEXT_PUBLIC_API_TIMEOUT
        value: "30000"
      - key: NEXT_PUBLIC_RETRY_ATTEMPTS
        value: "3"
      - key: NEXT_PUBLIC_RETRY_DELAY
        value: "1000"
    
    # Health check
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 60
