-- Migración para agregar tabla de respuestas a preguntas
-- Fecha: 2025-10-16

-- Tabla para almacenar las respuestas de los estudiantes a las preguntas genéricas
CREATE TABLE IF NOT EXISTS RESPUESTAS_PREGUNTAS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EVALUACION_ID INT NOT NULL,
    PREGUNTA_ID INT NOT NULL,
    RESPUESTA TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PREGUNTA_ID) REFERENCES PREGUNTAS(ID) ON DELETE CASCADE,
    INDEX idx_respuestas_evaluacion (EVALUACION_ID),
    INDEX idx_respuestas_pregunta (PREGUNTA_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Nota: EVALUACION_ID puede referirse a diferentes tablas según el tipo de evaluación
-- Para evaluaciones de docentes: puede ser EVALUACIONES_DETALLE.EVALUACION_ID
-- Para evaluaciones genéricas: puede ser un ID propio de EVALUACIONES_GENERICAS

-- Tabla para almacenar evaluaciones genéricas (no relacionadas con docentes)
CREATE TABLE IF NOT EXISTS EVALUACIONES_GENERICAS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CONFIGURACION_ID INT NOT NULL,
    DOCUMENTO_ESTUDIANTE VARCHAR(50) NOT NULL,
    COMENTARIO_GENERAL TEXT NULL,
    FECHA_EVALUACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO VARCHAR(20) DEFAULT 'completada',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CONFIGURACION_ID) REFERENCES CONFIGURACION_EVALUACION(ID) ON DELETE CASCADE,
    INDEX idx_evaluaciones_genericas_config (CONFIGURACION_ID),
    INDEX idx_evaluaciones_genericas_estudiante (DOCUMENTO_ESTUDIANTE),
    UNIQUE KEY unique_evaluacion_generica (CONFIGURACION_ID, DOCUMENTO_ESTUDIANTE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla para almacenar respuestas a aspectos de evaluaciones genéricas
CREATE TABLE IF NOT EXISTS EVALUACIONES_GENERICAS_DETALLE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EVALUACION_GENERICA_ID INT NOT NULL,
    ASPECTO_ID INT NULL,
    VALORACION_ID INT NULL,
    COMENTARIO TEXT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (EVALUACION_GENERICA_ID) REFERENCES EVALUACIONES_GENERICAS(ID) ON DELETE CASCADE,
    FOREIGN KEY (ASPECTO_ID) REFERENCES ASPECTOS_EVALUACION(ID) ON DELETE CASCADE,
    FOREIGN KEY (VALORACION_ID) REFERENCES ESCALA_VALORACION(ID) ON DELETE CASCADE,
    INDEX idx_evaluaciones_genericas_detalle_evaluacion (EVALUACION_GENERICA_ID),
    INDEX idx_evaluaciones_genericas_detalle_aspecto (ASPECTO_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
