-- Migración para crear tablas de autoevaluación docente
-- Fecha: 2025-11-30

-- Tabla principal de autoevaluación del docente
CREATE TABLE IF NOT EXISTS AUTOEVALUACION_DOCENTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DOCUMENTO_DOCENTE VARCHAR(20) NOT NULL,
    PERIODO VARCHAR(20) NOT NULL,
    COMPLETADA TINYINT(1) DEFAULT 0,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_docente_periodo (DOCUMENTO_DOCENTE, PERIODO),
    INDEX idx_docente (DOCUMENTO_DOCENTE),
    INDEX idx_periodo (PERIODO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla de detalle con las respuestas de cada aspecto
CREATE TABLE IF NOT EXISTS AUTOEVALUACION_DETALLE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    AUTOEVALUACION_ID INT NOT NULL,
    ASPECTO_ID INT NOT NULL,
    VALORACION VARCHAR(50) NOT NULL,
    PUNTAJE DECIMAL(3,2) DEFAULT 0.00,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AUTOEVALUACION_ID) REFERENCES AUTOEVALUACION_DOCENTE(ID) ON DELETE CASCADE,
    INDEX idx_autoevaluacion (AUTOEVALUACION_ID),
    INDEX idx_aspecto (ASPECTO_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Comentario: El peso de la autoevaluación es 20% y la evaluación de estudiantes 80%
-- Esto se calcula en la aplicación, no en la base de datos
