-- Migración para agregar tablas de preguntas
-- Fecha: 2025-01-09


CREATE TABLE IF NOT EXISTS PREGUNTAS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TEXTO TEXT NOT NULL,
    TIPO_PREGUNTA VARCHAR(50) NOT NULL,
    ORDEN INT DEFAULT 1,
    ACTIVO BOOLEAN DEFAULT TRUE,
    OPCIONES TEXT DEFAULT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS CONFIGURACION_PREGUNTAS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CONFIGURACION_EVALUACION_ID INT NOT NULL,
    PREGUNTA_ID INT NOT NULL,
    ORDEN INT DEFAULT 1,
    ACTIVO BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CONFIGURACION_EVALUACION_ID) REFERENCES CONFIGURACION_EVALUACION(ID) ON DELETE CASCADE,
    FOREIGN KEY (PREGUNTA_ID) REFERENCES PREGUNTAS(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insertar algunas preguntas de ejemplo
INSERT INTO PREGUNTAS (TEXTO, TIPO_PREGUNTA, ORDEN, ACTIVO, OPCIONES) VALUES
('¿Qué tan satisfecho está con la calidad de la enseñanza?', 'escala', 1, TRUE, NULL),
('¿Recomendaría este curso a otros estudiantes?', 'si_no', 2, TRUE, NULL),
('¿Cuál aspecto del curso considera más valioso?', 'seleccion_unica', 3, TRUE, 'Contenido teórico,Práctica aplicada,Material de apoyo,Metodología del docente'),
('Comentarios adicionales (opcional)', 'texto_largo', 4, TRUE, NULL);

-- Índices para mejorar rendimiento
CREATE INDEX idx_preguntas_activo ON PREGUNTAS(ACTIVO);
CREATE INDEX idx_preguntas_orden ON PREGUNTAS(ORDEN);
CREATE INDEX idx_config_preguntas_evaluacion ON CONFIGURACION_PREGUNTAS(CONFIGURACION_EVALUACION_ID);
CREATE INDEX idx_config_preguntas_pregunta ON CONFIGURACION_PREGUNTAS(PREGUNTA_ID);
CREATE INDEX idx_config_preguntas_activo ON CONFIGURACION_PREGUNTAS(ACTIVO);
